"""
retrain_trigger.py — Trigger the retraining DAG via the Airflow REST API.

Calls the Airflow 3.x REST API to initiate a new DAG run when drift is detected.
The unique dag_run_id (timestamp-based) ensures idempotency — if the monitor task
retries (Airflow default retries=2), a 409 Conflict response means the run was already
created and is handled gracefully.

CRITICAL: Airflow 3.x removed /api/v1 entirely. All calls must use /api/v2.
See: https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html
"""

import logging
from datetime import datetime
from typing import Any, Dict

import requests

logger = logging.getLogger(__name__)


def trigger_retrain_dag(
    airflow_host: str,
    dag_id: str,
    jwt_token: str,
) -> Dict[str, Any]:
    """Trigger a new DAG run via the Airflow 3.x REST API.

    Posts to the Airflow REST API endpoint to initiate a retraining pipeline run.
    Uses a timestamp-based dag_run_id to prevent duplicate runs on Airflow task retries.

    Args:
        airflow_host: Base URL of the Airflow webserver (e.g., "http://localhost:8080").
            Do NOT include a trailing slash.
        dag_id: The DAG ID to trigger (e.g., "crypto_volatility_pipeline").
            Typically set via env var RETRAIN_DAG_ID.
        jwt_token: Airflow API JWT Bearer token (from env var AIRFLOW_API_TOKEN).
            Generated by Airflow auth manager (see airflow users create).

    Returns:
        dict: The JSON response body from Airflow (contains dag_run_id, state, etc.)
            On 409 Conflict (duplicate dag_run_id), returns a dict with a 'skipped'
            key set to True instead of raising.

    Raises:
        requests.exceptions.HTTPError: For all non-2xx, non-409 HTTP responses.
        requests.exceptions.ConnectionError: If Airflow host is unreachable.
        requests.exceptions.Timeout: If the request exceeds 30 seconds.

    Notes:
        - Endpoint: POST /api/v2/dags/{dag_id}/dagRuns  (Airflow 3.x, NOT /api/v1)
        - Authentication: Bearer JWT token in Authorization header
        - dag_run_id format: drift_YYYYMMDDTHHMMSSZ (unique per-second; safe for retry)
        - conf.trigger_reason is passed through to the DAG run for audit logging
    """
    dag_run_id = f"drift_{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}"
    url = f"{airflow_host}/api/v2/dags/{dag_id}/dagRuns"

    headers = {
        "Authorization": f"Bearer {jwt_token}",
        "Content-Type": "application/json",
    }
    body = {
        "dag_run_id": dag_run_id,
        "conf": {"trigger_reason": "feature_drift"},
    }

    logger.info(
        "Triggering retrain DAG '%s' at %s (dag_run_id=%s)",
        dag_id,
        url,
        dag_run_id,
    )

    try:
        response = requests.post(url, json=body, headers=headers, timeout=30)
        response.raise_for_status()
    except requests.exceptions.HTTPError as exc:
        if exc.response is not None and exc.response.status_code == 409:
            # 409 Conflict: a DAG run with this ID already exists.
            # This is expected if the monitor task retries within the same second.
            logger.warning(
                "DAG run '%s' already exists (HTTP 409 Conflict) — skipping duplicate trigger",
                dag_run_id,
            )
            return {"skipped": True, "dag_run_id": dag_run_id, "reason": "conflict"}
        raise

    result = response.json()
    logger.info(
        "Retrain DAG run created: dag_run_id=%s, state=%s",
        result.get("dag_run_id"),
        result.get("state"),
    )
    return result
